all: main client server interfaccia

main: main.c
	gcc -o main main.c

client: client.c
	gcc -o client client.c

server: server.c
	gcc -o server server.c

interfaccia: interfaccia.c
	gcc -o interfaccia interfaccia.c

clean:
	rm -f main client server interfaccia